### ISSUE TITLE
Trouble installing software

### ISSUE THREAD

**Issue by sgpal** [booz-allen-hamilton/projectjellyfish#5]
Hi - I am trying to download and install Jellyfish and am getting the error pasted below. Appreciate any help you can provide.

================================================================================
    Error executing action `run` on resource 'execute[yum update]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of yum update -y ----
    STDOUT: Loaded plugins: amazon-id, rhui-lb
    STDERR: https://rhui2-cds02.us-east-1.aws.ce.redhat.com/pulp/repos//content/dist/rhel/rhui/server/7/7.0-1.el7/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
    Trying other mirror.
    https://rhui2-cds01.us-east-1.aws.ce.redhat.com/pulp/repos//content/dist/rhel/rhui/server/7/7.0-1.el7/x86_64/os/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
    Trying other mirror.

**Comment by mandeep170** [comment]
You can try commenting out the yum update line in the chef service mix recipe.rb file. Please comment that out and re-run.

**Comment by mandeep170** [comment]
it looks like your server cannot reach the red hat repositories. please check your internet connectivity on the server. Please make sure you are using a RHEL distribution for your server.
