### ISSUE TITLE
Couldn't find the link to update_servicemix_and_chef code

### ISSUE THREAD

**Issue by jayyvis** [booz-allen-hamilton/projectjellyfish#6]
I've installed the 3 components - marketplace, cloud engine & manageiq and configuring the integration between these as specified in the documentation. And I couldn't find the link to update_servicemix_and_chef code. 

### Following are the instructions where I got stuck now.

Configuring the Cloud Gateway - ManageIQ

4) Configuring Script to Update Cloud Engine

Under data, paste the code from [update_servicemix_and_chef code link], add the required information where it is requested within the script, and click Add

**Comment by jayyvis** [comment]
@mandeep170 Thought of reaching you to get help on this issue.

**Comment by mandeep170** [comment]
Let me check the documentation and get back to you.

**Comment by mandeep170** [comment]
The chef portion of the code was not open sourced in time, so please skip that step.

**Comment by jayyvis** [comment]
Thank you Mandeep. I'll do that.
